### PR TITLE
Bump watchos deployment target to 3.0

### PR DESCRIPTION
**Pull request by dchohfi**
Apple now requires that watchOS deployment target are minimum locked at 3.0 version.

https://forums.developer.apple.com/thread/108853

Could you create a tag after merging so we can use it on Carthage?

Thank you!

### CODE REVIEW

**Comment by dchohfi** [comment]
hey @kishikawakatsumi, any thoughts on this? I'm blocked to submit a watch target using Carthage. thank you.

**Comment by kishikawakatsumi** [comment]
It seems reasonable. But it is a breaking change. I also have been working on other breaking changes. Even if this PR is merged, the release will take a couple of times. In the meantime, please use your own folk. Thanks for reporting! @dchohfi

**Comment by dchohfi** [comment]
Cool, thank you!

**Comment by kishikawakatsumi** [comment]
Superseded https://github.com/kishikawakatsumi/KeychainAccess/pull/455

**Pull request merged**
