### PR TITLE
Remove installation instruction for Swift 2/watchOS 2

### PR DESCRIPTION
**Pull request by kishikawakatsumi**

### CODE REVIEW

**Comment by acegreen** [comment]
How do you access KeychainAccess from watchOS? I installed this library through cocoa pods but can't do let keychain = Keychain(service: bundleIdentifier)

without it saying that it can't recognize identifier. same line works on the iOS target

**Comment by kishikawakatsumi** [comment]
@acegreen What happens? Compile error? or Runtime error? Could you please show me more details.

**Comment by kishikawakatsumi** [comment]
KeychainAccess should work on watchOS 2. This PR just remove pre-release section.

**Comment by acegreen** [comment]
This is the error:

screen shot 2015-10-19 at 11 59 27 pm

**Comment by acegreen** [comment]
Only appears on watch extension

**Comment by acegreen** [comment]
Podfile configuration along with how it looks in my project

screen shot 2015-10-20 at 12 01 35 am

**Comment by kishikawakatsumi** [comment]
It has failed to setup. CocoaPods link only first target by default if a project has multiple targets. You should write `pod ...` to each target or use `link_with` to link multiple target.

**Comment by acegreen** [comment]
I tried various other options:

Option 1:

use_frameworks!

def shared_pods
  pod 'KeychainAccess'
end

target 'Chronic' do
  platform :ios, '8.0'
  pod 'CNPPopupController'
  pod 'DZNEmptyDataSet'
  shared_pods
end

target 'Chronic WatchKit Extension' do
  platform :watchos, '2.0'
  shared_pods
end

Option 2:

use_frameworks!
pod 'KeychainAccess'
pod 'CNPPopupController'
pod 'DZNEmptyDataSet'

Pod::Spec.new do |s|
# …
s.watchos.deployment_target = '2.0'
end

**Comment by kishikawakatsumi** [comment]
Please try like following:

```
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
platform :ios, '8.0'

target 'ExampleApp', :exclusive => true do
  pod 'KeychainAccess'
end

target 'ExampleApp WatchKit Extension', :exclusive => true do

end

target 'ExampleApp WatchKit 2 Extension', :exclusive => true do
  platform :watchos, '2.0'
  pod 'KeychainAccess'
end
```

**Comment by acegreen** [comment]
what about use_frameworks!?

**Comment by kishikawakatsumi** [comment]
Or could you send your project tome to further investigation?

**Comment by kishikawakatsumi** [comment]
@acegreen Sorry, `use_frameworks!` is needed. I forgot it since above sample was copied from my ObjC project.

**Comment by acegreen** [comment]
So I updated my Podfile as such

source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
platform :ios, '8.0'
use_frameworks!

target 'Chronic', :exclusive => true do
pod 'KeychainAccess'
pod 'CNPPopupController'
pod 'DZNEmptyDataSet'
end

target 'Chronic WatchKit Extension', :exclusive => true do
  platform :watchos, '2.0'
  pod 'KeychainAccess'
end

and I got the warning I got before with one of my options (see image)
screen shot 2015-10-20 at 12 11 27 am

**Comment by acegreen** [comment]
Now Keychain identifier not recognized on both targets

**Comment by kishikawakatsumi** [comment]
First, you should fix setup to follow messages of CocoaPods.

**Comment by kishikawakatsumi** [comment]
Or you can use other ways for setup. You can use pre-built framework https://github.com/kishikawakatsumi/KeychainAccess/releases or use Carthage https://github.com/Carthage/Carthage instead CocoaPods.

**Comment by acegreen** [comment]
Ok will copy the prebuilt frameworks. for sync between iOS and Apple Watch do I need to enable iCloud sharing in my capabilities? Also do we need to set accessibilities to the keys?

**Comment by acegreen** [comment]
After copying the prebuilt frameworks. the watch kit framework is causing the following error. though it was working for a little 

screen shot 2015-10-20 at 1 15 05 am

**Comment by kishikawakatsumi** [comment]
You should error message carefully first. You are wrong, you link iOS framework to watchOS app target. You should link the framework built for watchOS.

**Comment by acegreen** [comment]
No I was sure to put the right framework to the right target.

**Comment by kishikawakatsumi** [comment]
Can you send to me your project?

**Comment by acegreen** [comment]
I can't do that. its a production project. Can you Skype for a few minutes?

**Comment by acegreen** [comment]
Skype id: alelafy1989

**Pull request merged**
