### PR TITLE
Support Swift 1.2

### PR DESCRIPTION
**Pull request by kishikawakatsumi**

### CODE REVIEW

**Comment by garnett** [comment]
Any change to have this in master?

**Comment by kishikawakatsumi** [comment]
No I guess, but I will merge when Swift 1.2 and Xcode 6.3 will be released .

**Comment by Madimo** [comment]
Could you merge it please? There are many errors on Swift 1.2 using KeychainAccess. Thanks.

**Comment by kishikawakatsumi** [comment]
I will release in Today. I'm working final check.

**Comment by jlalvarez18** [comment]
:+1:

**Pull request merged**
