### PR TITLE
Update to Xcode 10.2 and Swift 5.0

### PR DESCRIPTION
**Pull request by taher-mosbah**
Run the migration assistant on framework and test apps, tests are green and 0 warnings.

### CODE REVIEW

**Comment by taher-mosbah** [comment]
Will update CI script as soon as Xcode 10.2 is available.

**Comment by detectedstealth** [comment]
@taher-mosbah with swift 5 and Xcode 10.2 now released any ETA on when this pull request would be merged? Just upgraded Xcode 10.2 and am getting "Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler"

**Comment by detectedstealth** [comment]
Never mind a carthage update --platform iOS solved my problem.

**Comment by m1entus** [comment]
+1 to merge

**Pull request closed without merging**
