### PR TITLE
Fixes issue #356 : Keychain with protocolType and accessGroup

### PR DESCRIPTION
**Pull request by yangyubo**
Refer issue #356 for detailed discussion.

### CODE REVIEW

**Comment by kishikawakatsumi** [comment]
@yangyubo Thanks! Somehow I overlooked existing behaviour. It looks good to me. I will merge soon after I test compatibility.

**Comment by yangyubo** [comment]
@kishikawakatsumi Any progress? Is there any other things I can do for this PR?

**Comment by jeff-h** [comment]
@kishikawakatsumi it would be great to get this rolled in if you're happy with it 👍

**Comment by jeff-h** [comment]
I've tested this now in my sample app (https://github.com/jeff-h/sharedKeychainAccessDemo) and it works great there. Would be great to see this PR rolled in.

**Comment by kishikawakatsumi** [comment]
Superseded https://github.com/kishikawakatsumi/KeychainAccess/pull/450

**Comment by kishikawakatsumi** [comment]
Superseded https://github.com/kishikawakatsumi/KeychainAccess/pull/450

**Comment by kishikawakatsumi** [comment]
Fixed by https://github.com/kishikawakatsumi/KeychainAccess/pull/450

**Pull request closed without merging**
