### PR TITLE
Support Swift 3.0

### PR DESCRIPTION
**Pull request by kishikawakatsumi**
### Support Swift 3.0
- [x] `id` is now mapped to `Any`

  [[SE-0116] Import Objective-C id as Swift Any type](https://github.com/apple/swift-evolution/blob/master/proposals/0116-id-as-any.md)
- [x] OptionSetType => OptionSet
- [x] ErrorType => ErrorProtocol => Error
- [x] AuthenticationPolicy to be UInt
- [x] Drop `NS` prefix
  - [x] NSData => Data
  - [x] NSURL => URL
  - [x] NSIndexSet => IndexSet
- [x] Lowercase enums

### Update to Xcode 8 recommended build settings 
- [x] Enable whole module optimazatin (by default on Xcode 8)
- [x] New code signing

### Tests on Travis CI with Xcode 8beta
- [x] Fix code signing issue

### Bug fixes
- [x] Enable to catch specific errors

### CODE REVIEW

**Comment by kishikawakatsumi** [comment]
Now all tests are passed! https://travis-ci.org/kishikawakatsumi/KeychainAccess/builds/155484718

**Comment by alokjha** [comment]
Is this been updated for Xcode 8 GM ?

**Comment by kishikawakatsumi** [comment]
@alokjha Yes. All tests are passed on Travis CI. Xcode 8 GM works on Travis CI.

**Comment by adamn** [comment]
It would be nice to get this closed and in master

**Comment by kishikawakatsumi** [comment]
Released 3.0.0! https://raw.githubusercontent.com/CocoaPods/Specs/aa104950445fbfc468afd067e895839f2de97060/Specs/KeychainAccess/3.0.0/KeychainAccess.podspec.json

**Pull request merged**
