### PR TITLE
Support Swift 2.3

### PR DESCRIPTION
**Pull request by kishikawakatsumi**

### CODE REVIEW

**Comment by kishikawakatsumi** [comment]
All tests are passed. https://travis-ci.org/kishikawakatsumi/KeychainAccess/builds/155481358

**Comment by AndrewBarba** [comment]
Any chance we could get this merged and update the pod version? Would really help now that the GM's are released

**Comment by kishikawakatsumi** [comment]
@AndrewBarba Xcode GM is released but Swift API is still changing unfortunately 😢  I'm going to merge this PR as soon as possible officially releasing Xcode 8 (around 16th?). I think specify branch in your podfile is fine, is there any problem in such way?

**Comment by liamnichols** [comment]
iOS 10 release is 13th (tues) :) 

I think people (well at least i do) have an issue with specifying a branch in the Podfile because it's not locking then library down to a specific release (I.e an accidentally `pod install` could technically break the build/app by mistake).

You could get around this buy supplying an explicit commit however I guess it's not as nice as specifying the version in the Podfile.

Either way, it should be fine to wait until Swift 2.3/3.0 is finalised on Tuesday :)

**Comment by AndrewBarba** [comment]
I think it makes sense to follow some other popular open source projects (ex. [Alamofire](https://github.com/Alamofire/Alamofire)) by merging this branch and releasing a minor version update to v2.4.0 then, perhaps more importantly, merge the Swift 3 branch and release a major version 3.0.0 as the future of the project. Apple highly recommends getting to Swift 3 as that is what is fully supported in Xcode 8 but we will still have the 2.4 release in Cocoapods for those who can't make the migration yet.

**Comment by kishikawakatsumi** [comment]
Released as v2.4.0 https://raw.githubusercontent.com/CocoaPods/Specs/85da28cda079827fdb72dc231a40e1f62bc3f869/Specs/KeychainAccess/2.4.0/KeychainAccess.podspec.json

**Pull request merged**
