### PR TITLE
Convert to Swift 4.2

### PR DESCRIPTION
**Pull request by IvoPintodaSilva**
Convert codebase to swift 4.2 and XCode 10

### CODE REVIEW

**Comment by Abeansits** [comment]
Merge plz 🙏

**Comment by kishikawakatsumi** [comment]
KeychainAccess is already compatible with Swift 4.2.

**Comment by alexterente** [comment]
Then it means there is other problem when trying to build it with carthage, 
"*** Downloading KeychainAccess.framework binary at "v3.1.1"
***  Skipped installing KeychainAccess.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.1 (swiftlang-902.0.48 clang-902.0.37.1) and the local version is 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1).""

**Comment by kishikawakatsumi** [comment]
@alexterente 

> If we point carthage to the branch from the pull request all works fine.

No. This is not an error. And merging this PR does NOT resolve it.

This message just says that the pre-built binary uploaded to GitHub Releases is incompatible with your environment. Then Carthage will automatically build the library from the source. No need to worry about this message. Simply ignore it.

A prebuilt binary helps to shorten the build time, but it is harmful behaviour in Swift because Swift's ABI is unstable. So I stopped using a prebuilt binary.

**Comment by kishikawakatsumi** [comment]
supersedes https://github.com/kishikawakatsumi/KeychainAccess/pull/404

**Pull request closed without merging**
