### PR TITLE
Add support for Mac Catalyst

### LINKED ISSUE #426: Support for UIKitForMac apps
Apple added the ability to enable building iOS apps for MacOS using catalyst, but it seems that the normal preprocessor branches of '#if os(iOS)' in the codebase are not good enough to differentiate between iOS and MacOS in this case, so we get a bunch of errors like 

`/Users/c890lma/projects/young-mobile-apps/ios-young/Pods/KeychainAccess/Lib/KeychainAccess/Keychain.swift:886:13: 'SecAddSharedWebCredential' is unavailable in UIKit for Mac`

Apple specifies that these checks should be done with
`#if !targetEnvironment(UIKitForMac)
// Code to exclude from Mac.
#endif`

So the iOS specific branches should probably include this check also?

### PR DESCRIPTION
**Pull request by tupperkion**
I've added some preprocessor macros that should (in theory) add support to Mac Catalyst.

To test these changes before they get merged:
```
pod 'KeychainAccess', :git => 'https://github.com/tupperkion/KeychainAccess.git'
```

Closes #426

### CODE REVIEW

**Comment by piercifani** [comment]
Can we get this in? We also really need this from our side

**Comment by SoolyChristy** [comment]
awesome

**Comment by quver** [comment]
Could you try to rebuild/fix unit tests?

**Comment by chrisCGL** [comment]
Let's get this in as soon as possible eh? :)

**Comment by kishikawakatsumi** [comment]
Superceded https://github.com/kishikawakatsumi/KeychainAccess/pull/448

**Pull request closed without merging**
